### ISSUE TITLE
404 on most pages after installing the plugin

### ISSUE THREAD

**Issue by Rogach** [neffets/redmine-stuff-to-do-plugin#10]
I tried installing the plugin (downloaded the files, ran the migration, restarted redmine), but after that most of the pages started returning 404: "The page you were trying to access doesn't exist or has been removed."

Exact list of my installation steps:
```
git clone https://github.com/neffets/redmine-stuff-to-do-plugin.git
bundle install
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
systemctl restart redmine
```

Here's the info from the logs:
```
Started GET "/settings/plugin/stuff_to_do_plugin" for 109.252.80.252 at 2018-06-18 06:57:10 +0000
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"stuff_to_do_plugin"}
  Current user: platon@pronko.ru (id=1)
  Rendered settings/plugin.html.erb within layouts/admin (4.9ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.2ms)
Completed 404 Not Found in 128ms (Views: 22.4ms | ActiveRecord: 25.0ms)
```

Redmine version: 3.2.1-2
OS: Ubuntu 16.04.4

After removing `plugins` directory stuff reverted to normal.

What could be the issue?

**Comment by neffets** [comment]
the install directory has to be named:
plugins/stuff_to_do_plugin/

otherwise it cannot find its css, templates etc.

Am June 18, 2018 7:02:15 AM UTC schrieb Rogach <notifications@github.com>:
>I tried installing the plugin (downloaded the files, ran the migration,
>restarted redmine), but after that most of the pages started returning
>404: "The page you were trying to access doesn't exist or has been
>removed."
>
>Exact list of my steps:
>```
>git clone https://github.com/neffets/redmine-stuff-to-do-plugin.git
>bundle install
>bundle exec rake redmine:plugins:migrate RAILS_ENV=production
>systemctl restart redmine
>```
>
>Here's the info from the logs:
>```
>Started GET "/settings/plugin/stuff_to_do_plugin" for 109.252.80.252 at
>2018-06-18 06:57:10 +0000
>Processing by SettingsController#plugin as HTML
>  Parameters: {"id"=>"stuff_to_do_plugin"}
>  Current user: platon@pronko.ru (id=1)
>  Rendered settings/plugin.html.erb within layouts/admin (4.9ms)
>Missing template, responding with 404
>  Rendered common/error.html.erb within layouts/base (0.2ms)
>Completed 404 Not Found in 128ms (Views: 22.4ms | ActiveRecord: 25.0ms)
>```
>
>Redmine version: 3.2.1-2
>OS: Ubuntu 16.04.4
>
>After removing `plugins` directory stuff reverted to normal.
>
>What could be the issue?
>
>
>
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/neffets/redmine-stuff-to-do-plugin/issues/10

-- 
Steffen Schüssler - mobil

**Comment by Rogach** [comment]
Yes, it's written right on the readme page - the problem is fixed. Sorry for bothering!

Thanks for the quick reply!
